services:
  eventstoredb:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true # let eventstore run without certificate (ok for local debug)
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 2113:2113

  eventstorepg:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    
  nats-cli:
    image: synadia/nats-server:nightly
    ports:
      - 8222:8222
    command: -js
    networks: [nats]

networks:
  nats:
    name: nats
